---
title: "Untitled"
author: "Tiantian Chen (tc2818)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## read data ##
#setwd("~/Fall2017-project4-grp2-master/data/data_sample/eachmovie_sample")
eachmovie<-read.csv("~/Fall2017-project4-grp2-master/data/data_sample/eachmovie_sample/data_train.csv",header = T)
eachmovie_test<-read.csv("~/Fall2017-project4-grp2-master/data/data_sample/eachmovie_sample/data_test.csv",header = T)
dim(eachmovie)


```


```{r}


ClusterModel<-function(dataset, C){
  ### STEP 1: initial guess for mu and gamma ###
  mu <- rep(1/C,C)
  gamma_est <- array(data = rep(1/6,C*6*length(unique(dataset$Movie))), dim = c(6,length(unique(dataset$Movie)), C)) # array: k j c

  ### STEP 2 ###
  N <-length(unique(dataset$User)) # N= 5055
  Pi<- matrix(NA, ncol = C, nrow = N)
  
  Pi_est<-matrix(NA, nrow=length(unique(dataset$User)), ncol = C)
  for(i in unique(dataset$User)){
    product<-rep(NA, C)
    for(c in 1:C){
      subdata<-dataset[dataset$User==i]
      product[c] <- 1
      for(j in unique(subdata$movie)){
        k<-subdata[subdata$movie == j,4]
        g_est<-gamma_est[k+1,sum(unique(dataset$Movie)<=j),c] 
        product[c]<-product*g_est
      }
    }
    s<- sum(mu*product)
    for(c in 1:C){
      Pi[sum(unque(dataset$User)<=i),c]<-mu[c]*product[c]/s
    }
  }
  
  ### STEP 3 & 4: iteration to update parameters ###

 
  while(change_mu >0.01 & change_gamma > 0.01){
    
    ## update mu
    for(c in 1:C){
      mu[c] = sum(Pi[,c])/N
    }
  
    ## update gamma estimation
    for(k in 0:5){
      for(c in 1:C){
       for(j in unique(dataset$Movie)){
      
         sub_j<-dataset[dataset$Movie==j,]
         # find user who have scored movie j
         set_of_i<- unique(sub_j$User)
       
         sum_1<-0
         sum_2<-0
         for(i in set_of_i){
           sum_1 <- sum_1+Pi[sum(unque(dataset$User)<=i),c]*(sub_j$Score[sub_j$User==i]==k)
           sum_2<-sum_2+Pi[sum(unque(dataset$User)<=i),c]
           }
         gamma_est[k+1,sum(unque(dataset$movie)<=j),c]<-sum_1/sum_2
       }}}
  
   ## calculate the change of mu and gamma
    change_mu<-norm(as.matrix(mu-mu_new))
    change_gamma<-norm(gamma_est-gamma_est_new)
  }
  
  ## return parameters
  return(list(mu, gamma_est))
}


### function to calculate the expectation of score ###

EstimateScore<-function(i1,b,dataset3){
  # input i1: user id; input b: movie id
  expect_score <- 0
  for(k in 0:6){
    sum_up <- 0
    for(c in 1:C){
    gamma_c<-gamma_from_em[,,c]
    I_i <- dataset3$Movie[dataset3$User == i1]
    pd <- 1
    for(j in I_i){
      pd <- pd*gamma_c[dataset3$Score[dataset3$User==i1 & dataset3$Movie==b],sum(unque(dataset3$movie)<=b)]
    }
    sum_up <- sum_up + mu[c]*gamma_c[k,sum(unque(dataset3$sub)<=b)] *pd
    sum_down <- sum_down + mu[c]*pd
    }
    expect_score <- expect_score + k*sum_up/sum_down
  }
  return(expect_score)
}

### cross-validation for choosing C
CV_Movie <- function(fold=5, dataset2, C_list){
  
  n = nrow(dataset2)
  c_number<-length(C_list)
  error_c <-0.770466 rep(NA, c_number)
  result_para<-vector("list",c_number)
  
  for(count in 1:c_number){
    
    C<-C_list[count]
    error_fold<-rep(NA, fold)
    for(f in 1:fold){
        
    rand <- sample(1:n, 5)
    test_data<-dataset2[rand,]
    train_data<-dataset2[-rand,]
      
    result_para[i] <- ClusterModel(train_set,C_list[p])
    mu_from_em <- result_para[i][[1]]
    gamma_from_em <- result_para[i][[2]]
      
    #calculate error
    test_data$expectation_score<-NA
    for(nn in n/5){
      user_i < -test_data[nn,"user"]
      movie_b <- test_data[nn,"movie"]
      test_data_1<-test_data[-nn,]
      test_data$expectation_score[nn]<-EstimateScore(user_i,movie_b,test_data_1)
    }
    #criterion 1: accuracy (error_fold)
    error_fold[fold]<-sum(test_data$score == test_data$expectation_score)/(n/5)
    
    #criterion 2: MAE
    ############
    ## TODO ####
    #############
    
    #criterion 3: ROC
    ###########
    ## TODO ###
    ##########
    }
   error_c[count] <-mean(error_fold) 
  }
  C_best<-C_list[which.min(error_c)]
  mu_best<-result_para[which.min(error_c)][[1]]
  gamma_best <- result_para[which.min(error_c)][[2]]
}

# calculte error on test data

eachmovie_test$expectation_score<-NA
n_test<-nrow(eachmovie_test)
for(row in 1:n_test){
  user_i <- eachmovie_test[row,"user"]
  movie_b <- eachmovie_test[row,"movie"]
      eachmovie_test_1<-eachmovie_test
      eachmovie_test$expectation_score<-EstimateScore(user_i,movie_b,eachmovie_test_1)
}


#criterion 1: accuracy
test_error<- sum(eachmovie_test$score == eachmovie_test$expectation_score)/n_test

#criterion 2: MAE
test_error2<- sum(abs(eachmovie_test$score - eachmovie_test$expectation_score))/n_test

#criterion 3: ROC
n=0;
m=0;
for(i in 1:nrow(eachmovie_test)){
if(eachmovie_test[i,4]>3 & eachmovie_test[i,5]>3){
 n=n+1
}else if(eachmovie_test[i,4]>3 & eachmovie_test[i,5]<=3){
  m=m+1
 }
}
test_error3=n/(n+m)




```

